Fix NDK x86 build.
Because gen-platforms.sh includes the current *bionic* directories, this
mistake in the android-9 crtbegin.c wasn't being noticed. It was using
the platform __stack_chk_fail_local.h instead of the missing local one.

  crtbegin.c:63:59: fatal error: ../../arch-x86/bionic/__stack_chk_fail_local.h: No such file or directory
   # include "../../arch-x86/bionic/__stack_chk_fail_local.h"

Bug: N/A
Test: builds
Change-Id: I8306cee1cf6d974ac5c3dae0c2927af3ceeb2cf6